language: node_js

cache: npm

sudo: required

services:
  - docker

matrix:
  include:
    # - os: linux
    #   node_js: '8'
    #   env:
    #     - BUILD_TASK=test
    # - os: linux
    #   node_js: '10'
    #   env:
    #     - BUILD_TASK=test
    # - os: linux
    #   node_js: '11'
    #   env:
    #     - BUILD_TASK=test
    - os: linux
      node_js: '8'
      env:
        - BUILD_TASK=prebuild
    - os: linux
      node_js: '10'
      env:
        - BUILD_TASK=prebuild
    - os: linux
      node_js: '11'
      env:
        - BUILD_TASK=prebuild
    # - os: osx
    #   node_js: '8'
    #   env:
    #     - BUILD_TASK=test
    - os: osx
      node_js: '8'
      env:
        - BUILD_TASK=prebuild
    # - os: osx
    #   node_js: '10'
    #   env:
    #     - BUILD_TASK=test
    - os: osx
      node_js: '10'
      env:
        - BUILD_TASK=prebuild
    # - os: osx
    #   node_js: '11'
    #   env:
    #     - BUILD_TASK=test
    - os: osx
      node_js: '11'
      env:
        - BUILD_TASK=prebuild

before_install:
  - chmod +x ./ci/$BUILD_TASK/$BUILD_TASK.sh;

install: true

script:
  - if [[ $BUILD_TASK != "prebuild" ]]; then
    cd ./ci/$BUILD_TASK;
    npm run $BUILD_TASK $TAG;
    fi
  - if [[ $BUILD_TASK == "prebuild" && $TRAVIS_TAG != "" ]]; then
    cd ./ci/$BUILD_TASK;
    npm run $BUILD_TASK $TAG;
    fi
