language: node_js

cache: npm

sudo: required

services:
  - docker

env:
  global:
    - OPENCV4NODEJS_DISABLE_AUTOBUILD=1

matrix:
  include:
    - os: linux
      env:
        - BUILD_TASK=test
          TAG=3.0.0-contrib-node6
    - os: linux
      env:
        - BUILD_TASK=test
          TAG=3.1.0-contrib-node6
    - os: linux
      env:
        - BUILD_TASK=test
          TAG=3.2.0-contrib-node6
    - os: linux
      env:
        - BUILD_TASK=test
          TAG=3.3.0-contrib-node6
    - os: linux
      env:
        - BUILD_TASK=test
          TAG=3.4.0-contrib-world-node6
    - os: linux
      env:
        - BUILD_TASK=test
          TAG=3.4.6-node6
    - os: linux
      env:
        - BUILD_TASK=test
          TAG=3.4.6-contrib-node6
    - os: linux
      env:
        - BUILD_TASK=test
          TAG=3.4.6-contrib-node8
    - os: linux
      env:
        - BUILD_TASK=test
          TAG=3.4.6-contrib-node10
    - os: linux
      node_js: '6'
      env:
        - BUILD_TASK=prebuild
    - os: linux
      node_js: '8'
      env:
        - BUILD_TASK=prebuild
    - os: linux
      node_js: '10'
      env:
        - BUILD_TASK=prebuild
    - os: linux
      node_js: '11'
      env:
        - BUILD_TASK=prebuild
    - os: osx
      node_js: '6'
      env:
        - BUILD_TASK=test
    - os: osx
      node_js: '6'
      env:
        - BUILD_TASK=prebuild
    - os: osx
      node_js: '8'
      env:
        - BUILD_TASK=test
    - os: osx
      node_js: '8'
      env:
        - BUILD_TASK=prebuild
    - os: osx
      node_js: '10'
      env:
        - BUILD_TASK=test
    - os: osx
      node_js: '10'
      env:
        - BUILD_TASK=prebuild
    - os: osx
      node_js: '11'
      env:
        - BUILD_TASK=test
    - os: osx
      node_js: '11'
      env:
        - BUILD_TASK=prebuild

before_install:
  - chmod +x ./ci/$BUILD_TASK/$BUILD_TASK.sh;

install: true

script:
  - if [[ $BUILD_TASK != "prebuild" ]]; then
    cd ./ci/$BUILD_TASK;
    npm run $BUILD_TASK $TAG;
    fi
  - if [[ $BUILD_TASK == "prebuild" && $TRAVIS_TAG != "" ]]; then
    cd ./ci/$BUILD_TASK;
    npm run $BUILD_TASK $TAG;
    fi

after_success:
  - if [ $BUILD_TASK = 'cover' ]; then
    npm install;
    npm run codecov -- -t $CODECOV_TOKEN;
    fi
