language: node_js

node_js:
  - '6'
  - '8'
  - '10'
  - 'node'

sudo: required

services:
  - docker

env:
  - BUILD_TASK=test
    TAG=3.0.0-contrib
  - BUILD_TASK=test
    TAG=3.1.0-contrib
  - BUILD_TASK=test
    TAG=3.2.0-contrib
  - BUILD_TASK=test
    TAG=3.3.0-contrib
  - BUILD_TASK=cover
    TAG=3.4.0-contrib
  - BUILD_TASK=test
    TAG=3.4.0-contrib-world
  - BUILD_TASK=test
    TAG=3.4.1-contrib
  - BUILD_TASK=test
    TAG=3.4.2-contrib
  - BUILD_TASK=test
    TAG=3.4.3
  - BUILD_TASK=test
    TAG=3.4.3-contrib
  - BUILD_TASK=prebuild
    TAG=3.4.3-contrib

before_install:
  - if [[ $BUILD_TASK != "prebuild" ]]; then
    chmod +x ./ci/$BUILD_TASK/$BUILD_TASK.sh
    fi

install: travis_wait 30 docker pull justadudewhohacks/opencv4nodejs-ci:$TAG

script:
  - if [[ $BUILD_TASK != "prebuild" ]]; then
    cd ./ci/$BUILD_TASK;
    npm run $BUILD_TASK $TAG;
    cd -;
    fi

after_success:
  - if [[ $TRAVIS_TAG != "" && $BUILD_TASK == "prebuild" ]]; then
    npm install;
    npm run prebuild -- -u $GITHUB_TOKEN;
    fi
  - if [ $BUILD_TASK = 'cover' ]; then
    npm install;
    npm run codecov -- -t $CODECOV_TOKEN;
    fi
